name: Build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo Linting Code...
          echo Code linted
          echo Executing Unit Tests...
          echo Unit Tests Executed
          echo Building Artifact...
          echo Artifact Built
          echo Uploading Artifact...
          echo Artifact Uploaded!
