on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy to ${{ inputs.environment }} environment
        run: |
          echo Deploying version ${{ inputs.tag }} to ${{ inputs.environment }}
          echo Deployment completed