on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: Output foofile
        run: cat foofile.txt
      - name: Output commit SHA
        run: Commit SHA $GITHUB_SHA
      - name: Deploy to ${{ inputs.environment }} environment
        run: |
          echo Deploying version ${{ inputs.tag }} to ${{ inputs.environment }}
          echo Deployment completed