name: Mainline workflow

on:
  check_suite:
    types: [completed]

jobs:
  process_output:
    runs-on: ubuntu-latest
    # if: github.event.check_suite.conclusion == 'success'
    # if: github.event.check_run.conclusion == 'success' && github.event.check_run.name == 'build'
    
    steps:
      - name: Get workflow output
        run: |
          echo "The tag created in the Build workflow is: ${{ github.event.check_run.output.git_tag }}"