name: Mainline workflow

on:
  workflow_run:
    workflows: [ Build ]
    types: [completed]

jobs:
  process_output:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Get workflow output
        run: |
          echo "The tag created in the Build workflow is: ${{ toJson(github.event.workflow_run.outputs) }}"