name: Deploy to Prod

on:
  workflow_dispatch: 
    inputs:
      tag:
        required: true
        type: string

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy
    with:
      environment: prod
      tag: ${{ inputs.tag }}